# ########################################################## MAIN APP
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radar
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://skyhook-io.github.io/helm-charts
    targetRevision: 1.15.0
    chart: radar
  destination:
    server: https://kubernetes.default.svc   
    namespace: radar
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

---
# ########################################################## INGRESS ROUTE

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radar-ingress
  namespace: radar
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`radar.andreiboghean.com`)
      services:
        - name: radar
          port: 9280
  tls:
    certResolver: default
    # - kind: Rule
      # match: Host(`argocd.andreiboghean.com`) && Header(`Content-Type`, `application/grpc`)
      # priority: 11
      # services:
        # - name: argocd-server
          # port: 80
          # scheme: h2c
---
# ########################################################## NUCLEAR SUPER PERMISSION PLS DONT HACK INTO THIS SERVICE
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: radar-cluster-admin
subjects:
  - kind: ServiceAccount
    name: radar
    namespace: radar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
