apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser-quantum
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/softwaredam/helm-charts/filebrowser-quantum
    targetRevision: 1.5.3-stable-2
    chart: filebrowser
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc   
    namespace: filebrowser-quantum
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filebrowser-quantum-ingress
  namespace: filebrowser-quantum
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`fbqt.andreiboghean.com`)
      services:
        - name: filebrowser-quantum
          port: 8080
  tls:
    certResolver: default

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: fbqt-config
spec:
  storageClassName: fbqt-manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubePVs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - nixos-server

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: 5tb-pv
spec:
  storageClassName: fbqt-manual
  capacity:
    storage: 5000G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/5TB_main"

