apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser-quantum
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/softwaredam/helm-charts/filebrowser-quantum
    targetRevision: v1.5.3-stable-2
    chart: filebrowser
    helm:
      valueFiles:
      - values.yaml
    server: https://kubernetes.default.svc   
    namespace: filebrowser-quantum
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filebrowser-quantum-ingress
  namespace: filebrowser-quantum
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`fbqt.andreiboghean.com`)
      services:
        - name: filebrowser-quantum
          port: 8080
  tls:
    certResolver: default


