apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser-quantum
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/softwaredam/helm-charts/filebrowser-quantum
    targetRevision: 1.5.3-stable-2
    chart: filebrowser
    helm:
      # valueFiles:
      # - values.yaml
      valuesObject:
        persistence:
          enabled: true
          keep: true
          # Global defaults - used if per-PVC settings are not specified
          storageClass: fbqt-manual
          accessMode: ReadWriteOnce
          # below: Per-PVC configuration - override global defaults as needed
          data:
            size: 5000G
          config:
            size: 8Gi
        config:
          server:
            port: 8080                      # port to listen on (default rn)
            # sources:                      #  validate:required,dive
              # - path: /mnt/5TB_main       # file system path. (Can be relative)  validate:required
  destination:
    server: https://kubernetes.default.svc   
    namespace: filebrowser-quantum
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: filebrowser-quantum-ingress
  namespace: filebrowser-quantum
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`fbqt.andreiboghean.com`)
      services:
        - name: filebrowser-quantum
          port: 8080
  tls:
    certResolver: default

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: fbqt-config
spec:
  storageClassName: fbqt-manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/kubePVs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - nixos-server

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: 5tb-pv
spec:
  storageClassName: fbqt-manual
  capacity:
    storage: 5000G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/5TB_main"

