persistence:
  enabled: true
  keep: true
  # Global defaults - used if per-PVC settings are not specified
  storageClass: fbqt-manual
  accessMode: ReadWriteOnce

  # Per-PVC configuration - override global defaults as needed
  data:
    size: 8Gi
  config:
    size: 5000G

config:
  server:
    port: 8080                              # port to listen on (default rn)
    sources:                                #  validate:required,dive
      - path: /mnt/5TB_main                 # file system path. (Can be relative)  validate:required
